# Generated by Django 5.0.6 on 2024-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_base', models.FileField(upload_to='video/')),
                ('file_pres', models.FileField(upload_to='results/')),
                ('file_cvs', models.FileField(upload_to='csv')),
            ],
        ),
    ]
